version: '3.8'

services:
  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    environment:
      - TIDB_PORT=4000
    volumes:
      - ./internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --store=unistore --path=""
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10080/status"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=tidb
      - DATABASE_PORT=4000
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
      - DATABASE_NAME=erp_db
    depends_on:
      tidb:
        condition: service_healthy