version: '3.8'

services:
  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    environment:
      - TIDB_PORT=4000
    volumes:
      - ./internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --store=unistore --path=""
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10080/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - erp-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      tidb:
        condition: service_healthy
    networks:
      - erp-network
    environment:
      - DB_HOST=tidb
      - DB_PORT=4000
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=erpdb

networks:
  erp-network:
    driver: bridge